### ISSUE TITLE
Number of duplicates

### ISSUE THREAD

**Issue by meibenny** [meibenny/CS375-SPG15-Project#1]
@dskoda1 With respect to the number of duplicates that should be created, maybe it is possible to make that random as well by allowing the duplicates to take a range from [p,r), where p = number of elements in the array so far, and r is the number of elements in the array.

**Comment by dskoda1** [comment]
@meibenny Well we have to decide how many duplicates of a certain number
we'd like. Specifically to differentiate from the non-duplicate input
generation the majority of the numbers should have at least 2 or more
instances. So how about a random number in the range [1, 50]? For larger
files of n > 10000 if we do [p, r) like you suggest then the latter half
will be basically the same number the entire time. Is that what were going
for with the duplicates? There won't be much sorting going on but I suppose
we are analyzing the algorithms behavior on inputs with many duplicates so
maybe it is the right option. We should have more discussion on this with
the 3 of us.

On Tue, Apr 14, 2015 at 5:08 PM, Benny Mei notifications@github.com wrote:

> @dskoda1 https://github.com/dskoda1 With respect to the number of
> duplicates that should be created, maybe it is possible to make that random
> as well by allowing the duplicates to take a range from [p,r), where p =
> number of elements in the array so far, and r is the number of elements in
> the array.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/meibenny/CS375-SPG15-Project/issues/1.

## 

David Skoda
Binghamton University '16
Computer Science

**Comment by meibenny** [comment]
Agreed. Let's have more discussion on tomorrow after class or Thursday before or after class.
